# -*- coding: utf-8 -*-
"""Predictive Maintenance Project - Akashdeep Das.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_uvso8i1fv2vDPqIIT03WKAFhxfBfKx
"""

!pip install kagglehub

import kagglehub

path = kagglehub.dataset_download("stephanmatzka/predictive-maintenance-dataset-ai4i-2020")

import pandas as pd
import os

df = pd.read_csv(os.path.join(path, "ai4i2020.csv"))
df.head()

import matplotlib.pyplot as plt
import seaborn as sns

df.columns = df.columns.str.strip()

print("Columns:", df.columns.tolist())

for col in df.columns:
    print(f"{col} unique values:", df[col].unique())

target_col = 'Machine failure'

if pd.api.types.is_categorical_dtype(df[target_col]):
    df[target_col] = df[target_col].cat.remove_unused_categories()

sns.countplot(x=target_col, data=df)
plt.title('Distribution of Equipment Failure')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

failure_counts = {
    'Tool Wear Failure': df['TWF'].sum(),
    'Heat Dissipation Failure': df['HDF'].sum(),
    'Power Failure': df['PWF'].sum(),
    'Overstrain Failure': df['OSF'].sum(),
    'Random Failure': df['RNF'].sum()
}

plt.figure(figsize=(10, 5))
sns.barplot(x=list(failure_counts.keys()), y=list(failure_counts.values()))
plt.title('Failure Type Distribution')
plt.ylabel('Number of Failures')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(x='Machine failure', data=df)
plt.title('Overall Machine Failure Distribution')
plt.xticks([0, 1], ['No Failure', 'Failure'])
plt.show()

df['air_temp_mean'] = df['Air temperature [K]'].rolling(window=5, min_periods=1).mean()
df['air_temp_std'] = df['Air temperature [K]'].rolling(window=5, min_periods=1).std()
df['torque_lag1'] = df['Torque [Nm]'].shift(1)
df['torque_lag3'] = df['Torque [Nm]'].shift(3)
df['rot_speed_change'] = df['Rotational speed [rpm]'].diff()
df = pd.get_dummies(df, columns=['Product ID', 'Type'], drop_first=True)

